# Video
vo=gpu
gpu-context=wayland
hwdec=vaapi
hwdec-codecs=all
interpolation=no
scale=bilinear
cscale=bilinear
dscale=bilinear
correct-downscaling=no
deband=no

# Audio
volume-max=150

# Subtitles
slang=en,eng
alang=en,eng
sub-auto=fuzzy

# OSD/UI 
osc=yes
osd-level=1

# Screenshots #
screenshot-format=png
screenshot-directory=~/Pictures/Mpv

# yt-dlp
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[height<=1080][fps<=60]+bestaudio/best[height<=1080]
ytdl-raw-options=no-playlist=,retries=10,fragment-retries=10,concurrent-fragments=4

# Profiles
[normal]
cache=auto
cache-secs=10
demuxer-readahead-secs=1
demuxer-hysteresis-secs=2
demuxer-max-bytes=96MiB
save-position-on-quit=no
video-sync=audio

[film]
cache=auto
cache-secs=30
demuxer-readahead-secs=1
demuxer-hysteresis-secs=5
demuxer-max-bytes=192MiB
save-position-on-quit=yes
video-sync=display-resample

[sports]
cache=no
demuxer-readahead-secs=1
demuxer-hysteresis-secs=0
demuxer-max-bytes=4MiB
save-position-on-quit=no
video-sync=audio

[default]
profile=normal
