#!/bin/sh
exec 2>&1
install -d -m 0770 -o root -g wheel /run/wpa_supplicant || exit 1
[ -r ./conf ] && . ./conf
exec wpa_supplicant -i "${WPA_INTERFACE:=wlan0}" \
                    -c "${CONF_FILE:=/etc/wpa_supplicant/home.conf}" \
                    ${OPTS:--s}
