permit persist setenv { PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin } :wheel
permit nopass bren as root cmd /usr/bin/poweroff
permit nopass bren as root cmd /usr/bin/reboot
permit nopass bren as root cmd /usr/bin/tee args /sys/power/state
